metadata_manifest: '/DCEG/CGF/Bioinformatics/Production/Bari/QIIME_test/test_manifest.txt'

## Directories
out_dir: '/DCEG/CGF/Bioinformatics/Production/Bari/QIIME_test/'
exec_dir: '/DCEG/CGF/Bioinformatics/Production/Bari/QIIME_pipeline/'
fastq_abs_path: '/DCEG/CGF/Sequencing/Illumina/MiSeq/PostRun_Analysis/Data/'

# Run mode
# standard (for CGR full run)
# external data - no symlinks, same entry, manual manifest generation - define manifest reqs
# report only - if we want more than the default report that's generated
  # report configs

## QIIME version
qiime_version: '2017.11'  # not yet implemented

## Analysis parameters
denoise_method: 'dada2' # not yet implemented
dada2_denoise:
  trim_left_forward: 0
  trim_left_reverse: 0
  truncate_length_forward: 0
  truncate_length_reverse: 0
phred_score: 33
demux_param: 'paired_end_demux'
input_type: 'SampleData[PairedEndSequencesWithQuality]'

## Cluster submission parameters
cluster_mode: 'local'  # 'qsub -q xlong.q -V -j y -o $path/to/QIIME2/logs/'  # options are 'qsub ...', 'local', 'dryrun', 'unlock'
num_jobs: 10
latency: 60
