# Step 1
project_dir: '/DCEG/Projects/Microbiome/CGR_MB/MicroBiome/Testing/Project_NP0084-MB4/'
metadata_manifest: 'NP0084-MB4_08_29_19_metadata_test_2.txt'

# Step 2-5
fastq_abs_path: '/DCEG/CGF/Sequencing/Illumina/MiSeq/PostRun_Analysis/Data/'

## QIIME version
qiime_version: '2017.11'

## Parameters
QUEUE: seq-gvcf.q
phred_score: 33
demux_param: 'paired_end_demux'
input_type: 'SampleData[PairedEndSequencesWithQuality]'
denoise_method: 'dada2'


## Script/Resource location
RESOURCES_DIR: '/resources'
