# CGR QIIME2 pipeline for microbiome analysis.
# 
# AUTHORS:
#     S. Sevilla Chill
#     W. Zhou
#     B. Ballew

## Manifest
metadata_manifest: '/DCEG/CGF/Bioinformatics/Production/Bari/QIIME_test/NP0084-MB4_10_14_19_metadata_ext.txt'

## Directories
out_dir: '/DCEG/CGF/Bioinformatics/Production/Bari/QIIME_test/2019'
exec_dir: '/DCEG/CGF/Bioinformatics/Production/Bari/QIIME_pipeline/'
fastq_abs_path: '/DCEG/CGF/Sequencing/Illumina/MiSeq/PostRun_Analysis/Data/'
temp_dir: '/scratch/ballewbj/test/'

# Run mode
# standard (for CGR full run)
# external data - no symlinks, same entry, manual manifest generation - define manifest reqs
# report only - if we want more than the default report that's generated
  # report configs

## QIIME version
qiime2_version: '2019.1'  # 2017.11 or 2019.1

## Analysis parameters
denoise_method: 'dada2' # not yet implemented
dada2_denoise:
  trim_left_forward: 0
  trim_left_reverse: 0
  truncate_length_forward: 0
  truncate_length_reverse: 0
phred_score: 33
demux_param: 'paired_end_demux'
input_type: 'SampleData[PairedEndSequencesWithQuality]'
filt_param: 1
sampling_depth: 10000
max_depth: 54000
classify_method: 'classify-sklearn'
reference_db:  # change based on qiime version
- '/DCEG/CGF/Bioinformatics/Production/Bari/refDatabases/scikit_0.20.2_q2_2019.1/gg-13-8-99-nb-classifier.qza'
- '/DCEG/CGF/Bioinformatics/Production/Bari/refDatabases/scikit_0.20.2_q2_2019.1/silva-132-99-nb-classifier.qza'

## Cluster submission parameters
cluster_mode: 'qsub -q long.q -V -j y -S /bin/bash -o /DCEG/CGF/Bioinformatics/Production/Bari/QIIME_test/2019/logs/ -pe by_node {threads}'  # options are 'qsub ...', 'local', 'dryrun', 'unlock'
num_jobs: 10
latency: 60
