# CGR QIIME2 pipeline for microbiome analysis.
# 
# AUTHORS:
#     W. Zhou
#     B. Ballew
#     Y. Wan
#     S. Sevilla Chill

## Manifest
metadata_manifest: '/path/to/manifest.txt'

## Directories
out_dir: '/path/to/project/directory/'
exec_dir: '/path/to/QIIME_pipeline/'
fastq_abs_path: '/path/to/fastqs/'  # internal runs only
temp_dir: '/path/to/scratch/'

## Run type
data_source: 'internal'  # 'external' or 'internal' (to CGR)
  # for external data, require an additional metadata columns called "fq1" and "fq2" with full path and file names for R1 and R2 fastqs (do they need to be zipped?)

## QIIME version
qiime2_sif: 'path/to/qiime2_2019.1.sif'

## Analysis parameters
dada2_denoise:
  trim_left_forward: 0
  trim_left_reverse: 0
  truncate_length_forward: 0
  truncate_length_reverse: 0
  min_fold_parent_over_abundance: 2.0
input_type: 'SampleData[PairedEndSequencesWithQuality]'
input_format: 'PairedEndFastqManifestPhred33' 
min_num_features_per_sample: 1  # TODO: enforce a minimum of 1 
min_num_reads_per_sample: 1
min_num_reads_per_feature: 1
min_num_samples_per_feature: 1
sampling_depth: 10000
max_depth: 54000
reference_db:  # change based on qiime version
- '/path/to/refDatabases/gg-13-8-99-515-806-nb-classifier.qza'
- '/path/to/refDatabases/silva-132-99-515-806-nb-classifier.qza'

## Cluster submission parameters
cluster_mode: 'sbatch -p myqueue --mem=64g --time=24:00:00 --output=/path/to/project/directory/logs/slurm-%j.out --cpus-per-task={threads}'
  # SGE example:    qsub -q myqueue.q -V -j y -S /bin/bash -o /path/to/project/directory/logs/ -pe by_node {threads}
  # slurm example:  sbatch --mem=64g --time=24:00:00 --output=/path/to/project/directory/logs/slurm-%j.out --cpus-per-task={threads}
num_jobs: 10
latency: 60
